### ISSUE TITLE
Jquery validation engine not working with Jquery 3.4.1

### ISSUE THREAD

**Issue by sannip** [posabsolute/jQuery-Validation-Engine#968]
Size() was deprecated years ago and removed in version 3. So, jquery validation engine fails with the below error.

jquery.validationEngine.js:968 Uncaught TypeError: form.find(...).size is not a function
    at _required (jquery.validationEngine.js:968)
    at Object._getErrorMessage (jquery.validationEngine.js:873)
    at Object._validateField (jquery.validationEngine.js:606)
    at HTMLInputElement.<anonymous> (jquery.validationEngine.js:363)
    at Function.each (jquery-3.4.1.js:367)
    at jQuery.fn.init.each (jquery-3.4.1.js:202)
    at Object._validateFields (jquery.validationEngine.js:359)
    at jQuery.fn.init.validate (jquery.validationEngine.js:120)
    at jQuery.fn.init.$.fn.validationEngine (jquery.validationEngine.js:2060)
    at ValidateAddOppForm (O10000293:930)

**Comment by dennybrandes** [comment]
I will check. Thanks for report.

**Comment by dennybrandes** [comment]
@posabsolute can you assign this issue to me please?

**Comment by dennybrandes** [comment]
it is fixed in version 3.0.0

**Comment by sannip** [comment]
Thanks
